### ISSUE TITLE
LMax calculator

### ISSUE THREAD

**Issue by pabggpnMSU** [bandframework/rose#10]
It would be nice if we could have a routine that estimates a value of LMax to use to advice the user. 

Kohn's term can be used to estimate (to first order) how much the free solution for a fixed value of L will experience a shift in its \delta due to the presence of the potential:

<img width="144" alt="image" src="https://user-images.githubusercontent.com/78561223/227795758-53c5ca0f-ce9d-428f-9211-576c25260722.png">

Then, we could have a threshold that if the differential cross section:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/78561223/227795817-c395dfb4-af5d-4a4e-8ee6-f4ffd72c7c84.png">

is impacted less than a given amount (user and problem dependent) for that change in \delta, we suggest this to be considered the maximum L. 

I'll ask Dick and Filomena to see if this makes sense, write down the math, and then we can implement it.

**Comment by beykyle** [comment]
By the way - this is typically done by breaking the loop over `l` when the phase shifts converge, given some criteria. This is probably more robust than pre-computing lmax, but will require refactoring the cross section calculations to use an explicit loop, with branching, which would probably be slower than the current implementation which takes advantage of `numpy.ufunc`s (e.g. `numpy.sum`)

**Comment by beykyle** [comment]
I have a branch where I've done this refactor, and use `numba.njit` to JIT compile, and it seems to actually be faster than the previous implementation, so I will add an in-loop l-cutoff.

**Comment by beykyle** [comment]
Closed in https://github.com/bandframework/rose/pull/64
