### ISSUE TITLE
CAT Plot Maker

### ISSUE THREAD

**Issue by pabggpnMSU** [bandframework/rose#11]
We should make a routine that trains the emulator for different configurations (number of basis, number of pillars, and maybe LMax or ERange?) and then creates the CAT plot so that the user can choose the optimal accuracy/speed trade off. 

I'll create that and we can later incorporate it directly into one of the ROSE functions.

**Comment by pabggpnMSU** [comment]
From Kyle's input: we should have the trained emulators into a dictionary so that all the information of how they were trained is stored and can be accessed later. This looks like the way to go

**Comment by pabggpnMSU** [comment]
[CATPlotMakerApril16.zip](https://github.com/odell/rose/files/11242568/CATPlotMakerApril16.zip)

Jupyter notebook to create CAT plots. Not fully commented yet, but functional. Produces figures like this:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/78561223/232321530-52c15b0a-4d80-40db-af09-6d8addf84b3d.png">

The text on the error and rate target was added externally. We can make all this an automatized part of ROSE later!

**Comment by beykyle** [comment]
Closed in https://github.com/bandframework/rose/pull/64
