### ISSUE TITLE
Update Tests

### ISSUE THREAD

**Issue by kylegodbey** [bandframework/rose#16]
Some tests are using the old name for rose. Some additional coverage for the tests should be added too, but that will be a separate issue.

**Comment by odell** [comment]
Just fixed the two cases I found. Agreed, additional coverage is needed.

**Comment by kylegodbey** [comment]
Any ideas for additional test coverage? Our 'unit' tests currently cover big units

**Comment by beykyle** [comment]
In my mind the most complicated, self-contained units are 
1. calculating matrix elements of the SE in a given reduced basis, in `ReducedBasisEmulator.__init__`
2. general scattering calculations in also in `ReducedBasisEmulator`
3. utility functions

I'd say these would be good places to start

**Comment by odell** [comment]
@pabggpnMSU and I talked about this at some point. I think one could also take a notebook that has been written to generate results, slice it up, and scale it back. Should provide several good tests.
