### ISSUE TITLE
High Fidelity Comparison

### ISSUE THREAD

**Issue by pabggpnMSU** [bandframework/rose#24]
Compare several High Fidelity solver like RK-4 and Numerov in a CAT plot and choose the best one to be the default for ROSE

**Comment by beykyle** [comment]
My analysis so far points to my python-native implementation of Numerov being slower and less accurate than `scipy.integrate.solve_ivp` (not that surprised):

![numerov_vs_RK_proton](https://github.com/bandframework/rose/assets/22779182/e1816137-5a8d-4753-82e2-ebe6625cf5db)

I'm trying to see if [numba.njit](https://numba.pydata.org/numba-doc/latest/glossary.html#term-nopython-mode) tilts the odds in Numerov's favor at all. I'll also probably try out this [calculable R-matrix solver](https://github.com/beykyle/lagrange-rmatrix) I wrote which uses a Lagrange-Legendre mesh. In principle, this should be pretty slow but very high-fidelity. Also, it is capable of doing coupled-channels and non-local potentials as well.

**Comment by beykyle** [comment]
Caveat in the above picture is that the CAT analysis only looked at a 27-Al(p,elastic) at a single energy. I wouldn't expect the overall trends to differ significantly in other problems tho.

**Comment by pabggpnMSU** [comment]
This is awesome Kyle! Million billion thanks for checking this.

Your CAT plots look great, I will probably steal the style for the paper :P

**Comment by beykyle** [comment]
@pabggpnMSU stealing the style should be easy to do once my branch gets merged/released. I've added the module [training.py](https://github.com/bandframework/rose/blob/feature-kd-global/src/rose/training.py), which has:

1. [a function](https://github.com/bandframework/rose/blob/feature-kd-global/src/rose/training.py#L61) for constructing a set of `ScatteringAmplitudeEmulator`s for CAT analysis without re-training
2. [A class](https://github.com/bandframework/rose/blob/feature-kd-global/src/rose/training.py#L130) doing the actual timing and error analysis 
3. [a function](https://github.com/bandframework/rose/blob/feature-kd-global/src/rose/training.py#L189) for CAT plotting 

I'll write up some more detailed report of what I've done when it's close to being ready (hopefully next week), including some notebooks demonstrating how these are used. I'll also try to to refactor the current tutorials to use these.

**Comment by beykyle** [comment]
Closed in https://github.com/bandframework/rose/pull/64
