### ISSUE TITLE
ScatteringAmplitudeEmulator.save/load issues

### ISSUE THREAD

**Issue by mosesyhc** [bandframework/rose#28]
Issue:
If `optical_potential` and its dependencies are not defined, running `rose.ScatteringAmplitudeEmulator.load` returns AttributeError

```AttributeError: Can't get attribute 'optical_potential' on <module '__main__'>```

To reproduce:
Take a saved `ScatteringAmplitudeEmulator` instance with filename `rose_emulator.pkl`, run `rose.ScatteringAmplitudeEmulator.load(f'rose_emulator.pkl')`.

**Comment by mosesyhc** [comment]
Saving causes AttributeError: Can't pickle local object 'SpinOrbitTerm.__init__.<locals>.<lambda>'

https://stackoverflow.com/questions/72339545/attributeerror-cant-pickle-local-object-locals-lambda

**Comment by kylegodbey** [comment]
Does this mean that saving trained models is completely broken at the moment?

**Comment by mosesyhc** [comment]
Yes it throws an AttributeError currently. 

On a side note, the unit test should include saving/loading.

**Comment by kylegodbey** [comment]
Made a new issue specifically for the unit tests: #63 

We will make sure we close that issue before pulling develop into main for v1.1

**Comment by beykyle** [comment]
I believe this is adressed in #64, saving and loading a trained model is now included in the testing suite,
