### ISSUE TITLE
Divide by zero in tutorial

### ISSUE THREAD

**Issue by pabggpnMSU** [bandframework/rose#34]
When running the cell to build the emulator in the first ROSE tutorial:
--------------------------------------
# let's build our first reduced basis emulator
emulator = rose.ScatteringAmplitudeEmulator.from_train(
    interactions,
    training_samples,
    l_max,
    n_basis=5,
    angles=angles / 180 * np.pi,
    hf_tols=[
        10 ** (-9),
        10 ** (-9),
    ],  # these are the relative and absolute tolerances for the HF Runge-Kutta solver
)
---------------------------------------

It returns at some point a warning:

RuntimeWarning: divide by zero encountered in scalar divide
  return np.hstack([1/(2*s_c) * (3 - (s[ii]/s_c)**2), 1/s[jj]])
/home/codespace/.python/current/lib/python3.10/site-packages/rose/scattering_amplitude_emulator.py:136: RuntimeWarning: invalid value encountered in divide
  self.f_c = -self.eta / (2*k*sin2) * np.exp(-1j*self.eta*np.log(sin2) + 2j*self.sigma_l[0])

I am not sure if this is happening because of the training region, but we should identify the cause of the issue and solve it before we release the tutorial into this world

**Comment by pabggpnMSU** [comment]
Hmmm I think it was because we were starting the angles at 0 and everything blows up. Yep, this was the issue, solved now!

**Comment by pabggpnMSU** [comment]
Well, now it is back and I have defined the angles between 1 and 179, so I don't know why it is having issues:

python3.10/site-packages/rose/utility.py:86: RuntimeWarning: divide by zero encountered in scalar divide
  return np.hstack([1/(2*s_c) * (3 - (s[ii]/s_c)**2), 1/s[jj]])

Anyone knows what this function in utility is calculating?

def regular_inverse_s(s, s_c):
    if isinstance(s, float) or isinstance(s, int):
        return 1/(2*s_c) * (3 - (s/s_c)**2) if s < s_c else 1/s
    else:
        ii = np.where(s <= s_c)[0]
        jj = np.where(s > s_c)[0]
        return np.hstack([1/(2*s_c) * (3 - (s[ii]/s_c)**2), 1/s[jj]])

**Comment by kylegodbey** [comment]
This bug still present?

**Comment by beykyle** [comment]
Closed in #64
