### ISSUE TITLE
calibration feedback 

### ISSUE THREAD

**Issue by mosesyhc** [bandframework/rose#5]
Feedback during MCMC sampling is desirable in calibration using surmise.  (Cross-referencing issue surmising/surmise#41)

> Once the emulator is built, surmise should run the calibration by building all the necessary components (the user of course still needs to provide a prior and a sample target, maybe the prior can be informed by the training region defined before). It would be nice (not only for ROSE, but for surmise in general) to have some feedback while it is running. These could include a bar showing progress, the current acceptance rate, and a corner plot of the parameters every now and then. The final results from surmise could be the visited parameters, the corner plot, a good version of the chains, and a final plot of the quantity the user was after (data and predictions/fit).

**Comment by pabggpnMSU** [comment]
For the progress feedback on the chains I was thinking something like this, which can be updated in real time as it progresses:

<img width="857" alt="Feedback" src="https://user-images.githubusercontent.com/78561223/227723509-8ffa1068-1776-4b9c-ac2b-2945657e0f17.png">

**Comment by pabggpnMSU** [comment]
And then, every XX samples (depends on the time the MCMC is taking) we could have an update on how the corner plot and the chains look, like this: 
<img width="922" alt="image" src="https://user-images.githubusercontent.com/78561223/227724397-58ea6d27-ba7f-40b9-9288-67cb6e5dfae4.png">

**Comment by mosesyhc** [comment]
mosesyhc/surmise@2f53b57 allows print progress to be switched on/off.

at this point tqdm is not added.

**Comment by mosesyhc** [comment]
Now scheduled in next release of surmise.

> [mosesyhc/surmise@2f53b57](https://github.com/mosesyhc/surmise/commit/2f53b57) allows print progress to be switched on/off.
> 
> at this point tqdm is not added.
