### ISSUE TITLE
Potential bug in HF solver

### ISSUE THREAD

**Issue by beykyle** [bandframework/rose#51]
In the rose HF solver `SchroedingerEquation.phi`, why does one pass in the mesh on which to evaluate phi, and then also the lower end of the domain `rho_0 `? In particular, in the case that `rho_0` is larger than the minimum of the mesh, the accuracy of the solution for `s < rho_0` is not guaranteed, see: https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.OdeSolution.html#scipy.integrate.OdeSolution

Additionally, any time `rho_0 !=`  the minimum of mesh, the initial conditions passed to scipy.integrate.solve_ivp are calculated incorrectly.

I would argue that rho_0 and phi_threshold should be removed as arguments, and the initial conditions be calculated based on the mesh.  Similar arguments hold for `SchroedingerEquation.delta` and `s_endpts`.

**Comment by beykyle** [comment]
I've implemented this in #49

**Comment by kylegodbey** [comment]
Did this give some numerical inaccuracies in our solutions? (Do the CAT plots need to be regenerated?)

**Comment by beykyle** [comment]
I believe not, as long as the defaults for `s_mesh` and `s_0` are used in `ScatteringAmplitudeEmulator.from_train`. This is the case for the tutorial, but without seeing the code used for the paper I don't know for sure.

**Comment by beykyle** [comment]
Closed in https://github.com/bandframework/rose/pull/64
