### ISSUE TITLE
Automatic link between ROSE and surmise for calibration

### ISSUE THREAD

**Issue by pabggpnMSU** [bandframework/rose#9]
[SurmiseLinkExample.zip](https://github.com/odell/rose/files/11080167/SurmiseLinkExample.zip)

The files contain an clean example of calibrating the optical potential for a given nucleus by emulating through ROSE and doing the sampling through surmise. It would be awesome if we could simplify this process into a default version that many users will use, while if they need they can modify the prior/data structure or other details in dependence to their specific problems. 

The flow we are thinking for a user wanting to do this is the following:

1) **Specify system details**: N and Z, scattered particle, L max, energy/energy range, quantity(s) of interest, sensible range of parameters.
2) **Select an emulator:** Train various versions of the ROSE emulators for different number of basis and pillars. Test and compare them on a CAT plot (would need to solve the high fidelity problem on a test set). Choose the appropriate one for the optimal trade-off between accuracy and speed.
3) **Prepare and run the MCMC calibration**: Specify the priors, data to be used for the calibration, and MCMC details (step sizes, number of chains and samples, etc). 
4) **Plot results:** Plot the corner plot, the chains of parameters visited, and how the calibrated model compares to the calibration data.

The file attached does points 1, 3, and 4 fully, while for 2 we train the emulator for 14 basis and pillars without running a CAT plot (will be developed separately). **The objective of this GitHub issue is: Can steps 3 and 4 be simplified and made into classes or functions in ROSE so that it is run something like this**:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/78561223/227791880-4ab4ed85-49a8-4f70-88e7-3c8705adef47.png">

<img width="496" alt="image" src="https://user-images.githubusercontent.com/78561223/227791932-aad120b2-13d5-48f2-a4a4-10cf26d3f7cd.png">

<img width="385" alt="image" src="https://user-images.githubusercontent.com/78561223/227791990-697cc64c-8bae-48df-89ab-e88b8c68ec56.png">

<img width="542" alt="image" src="https://user-images.githubusercontent.com/78561223/227792031-b4613475-b1d4-4f8f-ac00-853af31e6ced.png">

**Comment by kylegodbey** [comment]
Do we agree that this integration, for now, is handled on the surmise side? We can close this issue if so.

**Comment by odell** [comment]
That's how I see it, but I think that's @mosesyhc's call in the end.

**Comment by mosesyhc** [comment]
I would agree surmise will handle the integration, for now.
